url: https://vivianajo.com
baseurl: /agency-jekyll-theme/

# Site settings
title: VivianaJo.com
email: hello@vivianajo.com
description: "VivianaJo.com"


# Team names, titles and social links
people:
- name: Viviana
  pic: 1
  position: TBD
  social:
    - title: LinkedIn
      url: #https://www.linkedin.com/in/vivianajocruz/
    - title: stack-overflow
      url: #

# Build settings
markdown: kramdown
permalink: pretty
